# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from leap_motion/Human.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import geometry_msgs.msg
import leap_motion.msg
import std_msgs.msg

class Human(genpy.Message):
  _md5sum = "2817a017ab58b244566892058c4f6e6d"
  _type = "leap_motion/Human"
  _has_header = True #flag to mark the presence of a Header object
  _full_text = """std_msgs/Header header

# A unique ID for this Frame.
int32 lmc_frame_id

# How many hands were detected in the frame
int32 nr_of_hands

# How many fingers were detected in the frame
int32 nr_of_fingers

# How many gestures were detected in the frame
int32 nr_of_gestures

# The rate at which the Leap Motion software is providing frames of data (in frames per second). 
float32 current_frames_per_second

# A string containing a brief, human readable description of the Frame object. 
string to_string

# If there were any hands detected in the frame then the 
# hand.msg will be added here
Hand right_hand
Hand left_hand


================================================================================
MSG: std_msgs/Header
# Standard metadata for higher-level stamped data types.
# This is generally used to communicate timestamped data 
# in a particular coordinate frame.
# 
# sequence ID: consecutively increasing ID 
uint32 seq
#Two-integer timestamp that is expressed as:
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')
# time-handling sugar is provided by the client library
time stamp
#Frame this data is associated with
# 0: no frame
# 1: global frame
string frame_id

================================================================================
MSG: leap_motion/Hand
std_msgs/Header header

# A unique ID assigned to this Hand object
int32 lmc_hand_id

# This changed to between true/false depending if there's a hand detected in the LMC frame
bool is_present

# This changed to between true/false depending if there's a hand detected in the LMC frame
bool valid_gestures

# The duration of time this Hand has been visible to the Leap Motion Controller. 
float32 time_visible

# How confident we are with a given hand pose. 
# The confidence level ranges between 0.0 and 1.0 inclusive.
float32 confidence

# The following three angles are in radians!
float32 roll
float32 pitch
float32 yaw

# The direction vector
geometry_msgs/Vector3 direction

# The normal vector
geometry_msgs/Vector3 normal

# The angle between the fingers and the hand of a grab hand pose. 
# In radians
float32 grab_strength

# The distance between the thumb and index finger of a pinch hand pose. 
float32 pinch_strength

# The rate of change of the palm position in meters/second. 
float32[] palm_velocity

# The center position of the palm in meters from the Leap Motion Controller origin. 
geometry_msgs/Point palm_center

# The estimated width of the palm when the hand is in a flat position. 
float32 palm_width

# The radius (m) of a sphere fit to the curvature of this hand. 
float32 sphere_radius

# The center of a sphere fit to the curvature of this hand. 
float32[] sphere_center

# A string containing a brief, human readable description of the Hand object. 
string to_string 

# A list of fingers and gestures associated with this hand
Finger[] finger_list
Gesture[] gesture_list

# The arm associated with this hand
Arm arm

================================================================================
MSG: geometry_msgs/Vector3
# This represents a vector in free space. 
# It is only meant to represent a direction. Therefore, it does not
# make sense to apply a translation to it (e.g., when applying a 
# generic rigid transformation to a Vector3, tf2 will only apply the
# rotation). If you want your data to be translatable too, use the
# geometry_msgs/Point message instead.

float64 x
float64 y
float64 z
================================================================================
MSG: geometry_msgs/Point
# This contains the position of a point in free space
float64 x
float64 y
float64 z

================================================================================
MSG: leap_motion/Finger
std_msgs/Header header

# A unique id given to this finger
int32 lmc_finger_id

# The name of this finger. 
uint8 type

# The estimated length of the finger in meters. 
float32 length

# The estimated width of the finger in meters.
float32 width

# A string containing a brief, human readable description of the Finger object. 
string to_string

# List of bones associated with this finger
Bone[] bone_list
================================================================================
MSG: leap_motion/Bone
std_msgs/Header header

# The name of this bone. 
uint8 type

# The estimated length of the bone in meters.
float32 length

# The estimated with of the bone in meters.
float32 width

# A string containing a brief, human readable description of the Bone object. 
string to_string

# The base of the bone, closest to the wrist. 
geometry_msgs/Pose bone_start

# The end of the bone, closest to the finger tip. 
geometry_msgs/Pose bone_end

# The midpoint of the bone. 
float32[] center

================================================================================
MSG: geometry_msgs/Pose
# A representation of pose in free space, composed of position and orientation. 
Point position
Quaternion orientation

================================================================================
MSG: geometry_msgs/Quaternion
# This represents an orientation in free space in quaternion form.

float64 x
float64 y
float64 z
float64 w

================================================================================
MSG: leap_motion/Gesture
# A unique id given to this gesture
int32 lmc_gesture_id

# Reports whether this Gesture instance represents a valid Gesture. 
bool is_valid

# The elapsed duration of the recognized movement up to the frame containing this 
# Gesture object, in microseconds. 
int64 duration_us

# The elapsed duration in seconds.
float32 duration_s

# Recognized movements occur over time and have a beginning, a middle, and an end. 
# The 'state' attribute reports where in that sequence this Gesture object falls.
int32 gesture_state
### STATE_INVALID == -1
### STATE_START == 1
### STATE_UPDATE == 2
### STATE_STOP == 3

# The supported types of gestures. 
int32 gesture_type
### TYPE_INVALID == -1
### TYPE_SWIPE == 1
### TYPE_CIRCLE == 4
### TYPE_SCREEN_TAP == 5
### TYPE_KEY_TAP == 6

# A string containing a brief, human-readable description of this Gesture. 
string to_string

# The list of fingers, tools ids associated with this Gesture, if any. 
int32[] pointable_ids


================================================================================
MSG: leap_motion/Arm
std_msgs/Header header

# The position and orientation of the elbow. 
geometry_msgs/Pose elbow

# The position and orientation of the wrist. 
geometry_msgs/Pose wrist

# The midpoint of the forearm. 
float32[] center

# The direction vector of the forearm
geometry_msgs/Vector3 direction
"""
  __slots__ = ['header','lmc_frame_id','nr_of_hands','nr_of_fingers','nr_of_gestures','current_frames_per_second','to_string','right_hand','left_hand']
  _slot_types = ['std_msgs/Header','int32','int32','int32','int32','float32','string','leap_motion/Hand','leap_motion/Hand']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       header,lmc_frame_id,nr_of_hands,nr_of_fingers,nr_of_gestures,current_frames_per_second,to_string,right_hand,left_hand

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(Human, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.header is None:
        self.header = std_msgs.msg.Header()
      if self.lmc_frame_id is None:
        self.lmc_frame_id = 0
      if self.nr_of_hands is None:
        self.nr_of_hands = 0
      if self.nr_of_fingers is None:
        self.nr_of_fingers = 0
      if self.nr_of_gestures is None:
        self.nr_of_gestures = 0
      if self.current_frames_per_second is None:
        self.current_frames_per_second = 0.
      if self.to_string is None:
        self.to_string = ''
      if self.right_hand is None:
        self.right_hand = leap_motion.msg.Hand()
      if self.left_hand is None:
        self.left_hand = leap_motion.msg.Hand()
    else:
      self.header = std_msgs.msg.Header()
      self.lmc_frame_id = 0
      self.nr_of_hands = 0
      self.nr_of_fingers = 0
      self.nr_of_gestures = 0
      self.current_frames_per_second = 0.
      self.to_string = ''
      self.right_hand = leap_motion.msg.Hand()
      self.left_hand = leap_motion.msg.Hand()

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_3I().pack(_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs))
      _x = self.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.pack('<I%ss'%length, length, _x))
      _x = self
      buff.write(_get_struct_4if().pack(_x.lmc_frame_id, _x.nr_of_hands, _x.nr_of_fingers, _x.nr_of_gestures, _x.current_frames_per_second))
      _x = self.to_string
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.pack('<I%ss'%length, length, _x))
      _x = self
      buff.write(_get_struct_3I().pack(_x.right_hand.header.seq, _x.right_hand.header.stamp.secs, _x.right_hand.header.stamp.nsecs))
      _x = self.right_hand.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.pack('<I%ss'%length, length, _x))
      _x = self
      buff.write(_get_struct_i2B5f6d2f().pack(_x.right_hand.lmc_hand_id, _x.right_hand.is_present, _x.right_hand.valid_gestures, _x.right_hand.time_visible, _x.right_hand.confidence, _x.right_hand.roll, _x.right_hand.pitch, _x.right_hand.yaw, _x.right_hand.direction.x, _x.right_hand.direction.y, _x.right_hand.direction.z, _x.right_hand.normal.x, _x.right_hand.normal.y, _x.right_hand.normal.z, _x.right_hand.grab_strength, _x.right_hand.pinch_strength))
      length = len(self.right_hand.palm_velocity)
      buff.write(_struct_I.pack(length))
      pattern = '<%sf'%length
      buff.write(struct.pack(pattern, *self.right_hand.palm_velocity))
      _x = self
      buff.write(_get_struct_3d2f().pack(_x.right_hand.palm_center.x, _x.right_hand.palm_center.y, _x.right_hand.palm_center.z, _x.right_hand.palm_width, _x.right_hand.sphere_radius))
      length = len(self.right_hand.sphere_center)
      buff.write(_struct_I.pack(length))
      pattern = '<%sf'%length
      buff.write(struct.pack(pattern, *self.right_hand.sphere_center))
      _x = self.right_hand.to_string
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.pack('<I%ss'%length, length, _x))
      length = len(self.right_hand.finger_list)
      buff.write(_struct_I.pack(length))
      for val1 in self.right_hand.finger_list:
        _v1 = val1.header
        buff.write(_get_struct_I().pack(_v1.seq))
        _v2 = _v1.stamp
        _x = _v2
        buff.write(_get_struct_2I().pack(_x.secs, _x.nsecs))
        _x = _v1.frame_id
        length = len(_x)
        if python3 or type(_x) == unicode:
          _x = _x.encode('utf-8')
          length = len(_x)
        buff.write(struct.pack('<I%ss'%length, length, _x))
        _x = val1
        buff.write(_get_struct_iB2f().pack(_x.lmc_finger_id, _x.type, _x.length, _x.width))
        _x = val1.to_string
        length = len(_x)
        if python3 or type(_x) == unicode:
          _x = _x.encode('utf-8')
          length = len(_x)
        buff.write(struct.pack('<I%ss'%length, length, _x))
        length = len(val1.bone_list)
        buff.write(_struct_I.pack(length))
        for val2 in val1.bone_list:
          _v3 = val2.header
          buff.write(_get_struct_I().pack(_v3.seq))
          _v4 = _v3.stamp
          _x = _v4
          buff.write(_get_struct_2I().pack(_x.secs, _x.nsecs))
          _x = _v3.frame_id
          length = len(_x)
          if python3 or type(_x) == unicode:
            _x = _x.encode('utf-8')
            length = len(_x)
          buff.write(struct.pack('<I%ss'%length, length, _x))
          _x = val2
          buff.write(_get_struct_B2f().pack(_x.type, _x.length, _x.width))
          _x = val2.to_string
          length = len(_x)
          if python3 or type(_x) == unicode:
            _x = _x.encode('utf-8')
            length = len(_x)
          buff.write(struct.pack('<I%ss'%length, length, _x))
          _v5 = val2.bone_start
          _v6 = _v5.position
          _x = _v6
          buff.write(_get_struct_3d().pack(_x.x, _x.y, _x.z))
          _v7 = _v5.orientation
          _x = _v7
          buff.write(_get_struct_4d().pack(_x.x, _x.y, _x.z, _x.w))
          _v8 = val2.bone_end
          _v9 = _v8.position
          _x = _v9
          buff.write(_get_struct_3d().pack(_x.x, _x.y, _x.z))
          _v10 = _v8.orientation
          _x = _v10
          buff.write(_get_struct_4d().pack(_x.x, _x.y, _x.z, _x.w))
          length = len(val2.center)
          buff.write(_struct_I.pack(length))
          pattern = '<%sf'%length
          buff.write(struct.pack(pattern, *val2.center))
      length = len(self.right_hand.gesture_list)
      buff.write(_struct_I.pack(length))
      for val1 in self.right_hand.gesture_list:
        _x = val1
        buff.write(_get_struct_iBqf2i().pack(_x.lmc_gesture_id, _x.is_valid, _x.duration_us, _x.duration_s, _x.gesture_state, _x.gesture_type))
        _x = val1.to_string
        length = len(_x)
        if python3 or type(_x) == unicode:
          _x = _x.encode('utf-8')
          length = len(_x)
        buff.write(struct.pack('<I%ss'%length, length, _x))
        length = len(val1.pointable_ids)
        buff.write(_struct_I.pack(length))
        pattern = '<%si'%length
        buff.write(struct.pack(pattern, *val1.pointable_ids))
      _x = self
      buff.write(_get_struct_3I().pack(_x.right_hand.arm.header.seq, _x.right_hand.arm.header.stamp.secs, _x.right_hand.arm.header.stamp.nsecs))
      _x = self.right_hand.arm.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.pack('<I%ss'%length, length, _x))
      _x = self
      buff.write(_get_struct_14d().pack(_x.right_hand.arm.elbow.position.x, _x.right_hand.arm.elbow.position.y, _x.right_hand.arm.elbow.position.z, _x.right_hand.arm.elbow.orientation.x, _x.right_hand.arm.elbow.orientation.y, _x.right_hand.arm.elbow.orientation.z, _x.right_hand.arm.elbow.orientation.w, _x.right_hand.arm.wrist.position.x, _x.right_hand.arm.wrist.position.y, _x.right_hand.arm.wrist.position.z, _x.right_hand.arm.wrist.orientation.x, _x.right_hand.arm.wrist.orientation.y, _x.right_hand.arm.wrist.orientation.z, _x.right_hand.arm.wrist.orientation.w))
      length = len(self.right_hand.arm.center)
      buff.write(_struct_I.pack(length))
      pattern = '<%sf'%length
      buff.write(struct.pack(pattern, *self.right_hand.arm.center))
      _x = self
      buff.write(_get_struct_3d3I().pack(_x.right_hand.arm.direction.x, _x.right_hand.arm.direction.y, _x.right_hand.arm.direction.z, _x.left_hand.header.seq, _x.left_hand.header.stamp.secs, _x.left_hand.header.stamp.nsecs))
      _x = self.left_hand.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.pack('<I%ss'%length, length, _x))
      _x = self
      buff.write(_get_struct_i2B5f6d2f().pack(_x.left_hand.lmc_hand_id, _x.left_hand.is_present, _x.left_hand.valid_gestures, _x.left_hand.time_visible, _x.left_hand.confidence, _x.left_hand.roll, _x.left_hand.pitch, _x.left_hand.yaw, _x.left_hand.direction.x, _x.left_hand.direction.y, _x.left_hand.direction.z, _x.left_hand.normal.x, _x.left_hand.normal.y, _x.left_hand.normal.z, _x.left_hand.grab_strength, _x.left_hand.pinch_strength))
      length = len(self.left_hand.palm_velocity)
      buff.write(_struct_I.pack(length))
      pattern = '<%sf'%length
      buff.write(struct.pack(pattern, *self.left_hand.palm_velocity))
      _x = self
      buff.write(_get_struct_3d2f().pack(_x.left_hand.palm_center.x, _x.left_hand.palm_center.y, _x.left_hand.palm_center.z, _x.left_hand.palm_width, _x.left_hand.sphere_radius))
      length = len(self.left_hand.sphere_center)
      buff.write(_struct_I.pack(length))
      pattern = '<%sf'%length
      buff.write(struct.pack(pattern, *self.left_hand.sphere_center))
      _x = self.left_hand.to_string
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.pack('<I%ss'%length, length, _x))
      length = len(self.left_hand.finger_list)
      buff.write(_struct_I.pack(length))
      for val1 in self.left_hand.finger_list:
        _v11 = val1.header
        buff.write(_get_struct_I().pack(_v11.seq))
        _v12 = _v11.stamp
        _x = _v12
        buff.write(_get_struct_2I().pack(_x.secs, _x.nsecs))
        _x = _v11.frame_id
        length = len(_x)
        if python3 or type(_x) == unicode:
          _x = _x.encode('utf-8')
          length = len(_x)
        buff.write(struct.pack('<I%ss'%length, length, _x))
        _x = val1
        buff.write(_get_struct_iB2f().pack(_x.lmc_finger_id, _x.type, _x.length, _x.width))
        _x = val1.to_string
        length = len(_x)
        if python3 or type(_x) == unicode:
          _x = _x.encode('utf-8')
          length = len(_x)
        buff.write(struct.pack('<I%ss'%length, length, _x))
        length = len(val1.bone_list)
        buff.write(_struct_I.pack(length))
        for val2 in val1.bone_list:
          _v13 = val2.header
          buff.write(_get_struct_I().pack(_v13.seq))
          _v14 = _v13.stamp
          _x = _v14
          buff.write(_get_struct_2I().pack(_x.secs, _x.nsecs))
          _x = _v13.frame_id
          length = len(_x)
          if python3 or type(_x) == unicode:
            _x = _x.encode('utf-8')
            length = len(_x)
          buff.write(struct.pack('<I%ss'%length, length, _x))
          _x = val2
          buff.write(_get_struct_B2f().pack(_x.type, _x.length, _x.width))
          _x = val2.to_string
          length = len(_x)
          if python3 or type(_x) == unicode:
            _x = _x.encode('utf-8')
            length = len(_x)
          buff.write(struct.pack('<I%ss'%length, length, _x))
          _v15 = val2.bone_start
          _v16 = _v15.position
          _x = _v16
          buff.write(_get_struct_3d().pack(_x.x, _x.y, _x.z))
          _v17 = _v15.orientation
          _x = _v17
          buff.write(_get_struct_4d().pack(_x.x, _x.y, _x.z, _x.w))
          _v18 = val2.bone_end
          _v19 = _v18.position
          _x = _v19
          buff.write(_get_struct_3d().pack(_x.x, _x.y, _x.z))
          _v20 = _v18.orientation
          _x = _v20
          buff.write(_get_struct_4d().pack(_x.x, _x.y, _x.z, _x.w))
          length = len(val2.center)
          buff.write(_struct_I.pack(length))
          pattern = '<%sf'%length
          buff.write(struct.pack(pattern, *val2.center))
      length = len(self.left_hand.gesture_list)
      buff.write(_struct_I.pack(length))
      for val1 in self.left_hand.gesture_list:
        _x = val1
        buff.write(_get_struct_iBqf2i().pack(_x.lmc_gesture_id, _x.is_valid, _x.duration_us, _x.duration_s, _x.gesture_state, _x.gesture_type))
        _x = val1.to_string
        length = len(_x)
        if python3 or type(_x) == unicode:
          _x = _x.encode('utf-8')
          length = len(_x)
        buff.write(struct.pack('<I%ss'%length, length, _x))
        length = len(val1.pointable_ids)
        buff.write(_struct_I.pack(length))
        pattern = '<%si'%length
        buff.write(struct.pack(pattern, *val1.pointable_ids))
      _x = self
      buff.write(_get_struct_3I().pack(_x.left_hand.arm.header.seq, _x.left_hand.arm.header.stamp.secs, _x.left_hand.arm.header.stamp.nsecs))
      _x = self.left_hand.arm.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.pack('<I%ss'%length, length, _x))
      _x = self
      buff.write(_get_struct_14d().pack(_x.left_hand.arm.elbow.position.x, _x.left_hand.arm.elbow.position.y, _x.left_hand.arm.elbow.position.z, _x.left_hand.arm.elbow.orientation.x, _x.left_hand.arm.elbow.orientation.y, _x.left_hand.arm.elbow.orientation.z, _x.left_hand.arm.elbow.orientation.w, _x.left_hand.arm.wrist.position.x, _x.left_hand.arm.wrist.position.y, _x.left_hand.arm.wrist.position.z, _x.left_hand.arm.wrist.orientation.x, _x.left_hand.arm.wrist.orientation.y, _x.left_hand.arm.wrist.orientation.z, _x.left_hand.arm.wrist.orientation.w))
      length = len(self.left_hand.arm.center)
      buff.write(_struct_I.pack(length))
      pattern = '<%sf'%length
      buff.write(struct.pack(pattern, *self.left_hand.arm.center))
      _x = self
      buff.write(_get_struct_3d().pack(_x.left_hand.arm.direction.x, _x.left_hand.arm.direction.y, _x.left_hand.arm.direction.z))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      if self.header is None:
        self.header = std_msgs.msg.Header()
      if self.right_hand is None:
        self.right_hand = leap_motion.msg.Hand()
      if self.left_hand is None:
        self.left_hand = leap_motion.msg.Hand()
      end = 0
      _x = self
      start = end
      end += 12
      (_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs,) = _get_struct_3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.header.frame_id = str[start:end].decode('utf-8')
      else:
        self.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 20
      (_x.lmc_frame_id, _x.nr_of_hands, _x.nr_of_fingers, _x.nr_of_gestures, _x.current_frames_per_second,) = _get_struct_4if().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.to_string = str[start:end].decode('utf-8')
      else:
        self.to_string = str[start:end]
      _x = self
      start = end
      end += 12
      (_x.right_hand.header.seq, _x.right_hand.header.stamp.secs, _x.right_hand.header.stamp.nsecs,) = _get_struct_3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.right_hand.header.frame_id = str[start:end].decode('utf-8')
      else:
        self.right_hand.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 82
      (_x.right_hand.lmc_hand_id, _x.right_hand.is_present, _x.right_hand.valid_gestures, _x.right_hand.time_visible, _x.right_hand.confidence, _x.right_hand.roll, _x.right_hand.pitch, _x.right_hand.yaw, _x.right_hand.direction.x, _x.right_hand.direction.y, _x.right_hand.direction.z, _x.right_hand.normal.x, _x.right_hand.normal.y, _x.right_hand.normal.z, _x.right_hand.grab_strength, _x.right_hand.pinch_strength,) = _get_struct_i2B5f6d2f().unpack(str[start:end])
      self.right_hand.is_present = bool(self.right_hand.is_present)
      self.right_hand.valid_gestures = bool(self.right_hand.valid_gestures)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%sf'%length
      start = end
      end += struct.calcsize(pattern)
      self.right_hand.palm_velocity = struct.unpack(pattern, str[start:end])
      _x = self
      start = end
      end += 32
      (_x.right_hand.palm_center.x, _x.right_hand.palm_center.y, _x.right_hand.palm_center.z, _x.right_hand.palm_width, _x.right_hand.sphere_radius,) = _get_struct_3d2f().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%sf'%length
      start = end
      end += struct.calcsize(pattern)
      self.right_hand.sphere_center = struct.unpack(pattern, str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.right_hand.to_string = str[start:end].decode('utf-8')
      else:
        self.right_hand.to_string = str[start:end]
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.right_hand.finger_list = []
      for i in range(0, length):
        val1 = leap_motion.msg.Finger()
        _v21 = val1.header
        start = end
        end += 4
        (_v21.seq,) = _get_struct_I().unpack(str[start:end])
        _v22 = _v21.stamp
        _x = _v22
        start = end
        end += 8
        (_x.secs, _x.nsecs,) = _get_struct_2I().unpack(str[start:end])
        start = end
        end += 4
        (length,) = _struct_I.unpack(str[start:end])
        start = end
        end += length
        if python3:
          _v21.frame_id = str[start:end].decode('utf-8')
        else:
          _v21.frame_id = str[start:end]
        _x = val1
        start = end
        end += 13
        (_x.lmc_finger_id, _x.type, _x.length, _x.width,) = _get_struct_iB2f().unpack(str[start:end])
        start = end
        end += 4
        (length,) = _struct_I.unpack(str[start:end])
        start = end
        end += length
        if python3:
          val1.to_string = str[start:end].decode('utf-8')
        else:
          val1.to_string = str[start:end]
        start = end
        end += 4
        (length,) = _struct_I.unpack(str[start:end])
        val1.bone_list = []
        for i in range(0, length):
          val2 = leap_motion.msg.Bone()
          _v23 = val2.header
          start = end
          end += 4
          (_v23.seq,) = _get_struct_I().unpack(str[start:end])
          _v24 = _v23.stamp
          _x = _v24
          start = end
          end += 8
          (_x.secs, _x.nsecs,) = _get_struct_2I().unpack(str[start:end])
          start = end
          end += 4
          (length,) = _struct_I.unpack(str[start:end])
          start = end
          end += length
          if python3:
            _v23.frame_id = str[start:end].decode('utf-8')
          else:
            _v23.frame_id = str[start:end]
          _x = val2
          start = end
          end += 9
          (_x.type, _x.length, _x.width,) = _get_struct_B2f().unpack(str[start:end])
          start = end
          end += 4
          (length,) = _struct_I.unpack(str[start:end])
          start = end
          end += length
          if python3:
            val2.to_string = str[start:end].decode('utf-8')
          else:
            val2.to_string = str[start:end]
          _v25 = val2.bone_start
          _v26 = _v25.position
          _x = _v26
          start = end
          end += 24
          (_x.x, _x.y, _x.z,) = _get_struct_3d().unpack(str[start:end])
          _v27 = _v25.orientation
          _x = _v27
          start = end
          end += 32
          (_x.x, _x.y, _x.z, _x.w,) = _get_struct_4d().unpack(str[start:end])
          _v28 = val2.bone_end
          _v29 = _v28.position
          _x = _v29
          start = end
          end += 24
          (_x.x, _x.y, _x.z,) = _get_struct_3d().unpack(str[start:end])
          _v30 = _v28.orientation
          _x = _v30
          start = end
          end += 32
          (_x.x, _x.y, _x.z, _x.w,) = _get_struct_4d().unpack(str[start:end])
          start = end
          end += 4
          (length,) = _struct_I.unpack(str[start:end])
          pattern = '<%sf'%length
          start = end
          end += struct.calcsize(pattern)
          val2.center = struct.unpack(pattern, str[start:end])
          val1.bone_list.append(val2)
        self.right_hand.finger_list.append(val1)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.right_hand.gesture_list = []
      for i in range(0, length):
        val1 = leap_motion.msg.Gesture()
        _x = val1
        start = end
        end += 25
        (_x.lmc_gesture_id, _x.is_valid, _x.duration_us, _x.duration_s, _x.gesture_state, _x.gesture_type,) = _get_struct_iBqf2i().unpack(str[start:end])
        val1.is_valid = bool(val1.is_valid)
        start = end
        end += 4
        (length,) = _struct_I.unpack(str[start:end])
        start = end
        end += length
        if python3:
          val1.to_string = str[start:end].decode('utf-8')
        else:
          val1.to_string = str[start:end]
        start = end
        end += 4
        (length,) = _struct_I.unpack(str[start:end])
        pattern = '<%si'%length
        start = end
        end += struct.calcsize(pattern)
        val1.pointable_ids = struct.unpack(pattern, str[start:end])
        self.right_hand.gesture_list.append(val1)
      _x = self
      start = end
      end += 12
      (_x.right_hand.arm.header.seq, _x.right_hand.arm.header.stamp.secs, _x.right_hand.arm.header.stamp.nsecs,) = _get_struct_3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.right_hand.arm.header.frame_id = str[start:end].decode('utf-8')
      else:
        self.right_hand.arm.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 112
      (_x.right_hand.arm.elbow.position.x, _x.right_hand.arm.elbow.position.y, _x.right_hand.arm.elbow.position.z, _x.right_hand.arm.elbow.orientation.x, _x.right_hand.arm.elbow.orientation.y, _x.right_hand.arm.elbow.orientation.z, _x.right_hand.arm.elbow.orientation.w, _x.right_hand.arm.wrist.position.x, _x.right_hand.arm.wrist.position.y, _x.right_hand.arm.wrist.position.z, _x.right_hand.arm.wrist.orientation.x, _x.right_hand.arm.wrist.orientation.y, _x.right_hand.arm.wrist.orientation.z, _x.right_hand.arm.wrist.orientation.w,) = _get_struct_14d().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%sf'%length
      start = end
      end += struct.calcsize(pattern)
      self.right_hand.arm.center = struct.unpack(pattern, str[start:end])
      _x = self
      start = end
      end += 36
      (_x.right_hand.arm.direction.x, _x.right_hand.arm.direction.y, _x.right_hand.arm.direction.z, _x.left_hand.header.seq, _x.left_hand.header.stamp.secs, _x.left_hand.header.stamp.nsecs,) = _get_struct_3d3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.left_hand.header.frame_id = str[start:end].decode('utf-8')
      else:
        self.left_hand.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 82
      (_x.left_hand.lmc_hand_id, _x.left_hand.is_present, _x.left_hand.valid_gestures, _x.left_hand.time_visible, _x.left_hand.confidence, _x.left_hand.roll, _x.left_hand.pitch, _x.left_hand.yaw, _x.left_hand.direction.x, _x.left_hand.direction.y, _x.left_hand.direction.z, _x.left_hand.normal.x, _x.left_hand.normal.y, _x.left_hand.normal.z, _x.left_hand.grab_strength, _x.left_hand.pinch_strength,) = _get_struct_i2B5f6d2f().unpack(str[start:end])
      self.left_hand.is_present = bool(self.left_hand.is_present)
      self.left_hand.valid_gestures = bool(self.left_hand.valid_gestures)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%sf'%length
      start = end
      end += struct.calcsize(pattern)
      self.left_hand.palm_velocity = struct.unpack(pattern, str[start:end])
      _x = self
      start = end
      end += 32
      (_x.left_hand.palm_center.x, _x.left_hand.palm_center.y, _x.left_hand.palm_center.z, _x.left_hand.palm_width, _x.left_hand.sphere_radius,) = _get_struct_3d2f().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%sf'%length
      start = end
      end += struct.calcsize(pattern)
      self.left_hand.sphere_center = struct.unpack(pattern, str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.left_hand.to_string = str[start:end].decode('utf-8')
      else:
        self.left_hand.to_string = str[start:end]
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.left_hand.finger_list = []
      for i in range(0, length):
        val1 = leap_motion.msg.Finger()
        _v31 = val1.header
        start = end
        end += 4
        (_v31.seq,) = _get_struct_I().unpack(str[start:end])
        _v32 = _v31.stamp
        _x = _v32
        start = end
        end += 8
        (_x.secs, _x.nsecs,) = _get_struct_2I().unpack(str[start:end])
        start = end
        end += 4
        (length,) = _struct_I.unpack(str[start:end])
        start = end
        end += length
        if python3:
          _v31.frame_id = str[start:end].decode('utf-8')
        else:
          _v31.frame_id = str[start:end]
        _x = val1
        start = end
        end += 13
        (_x.lmc_finger_id, _x.type, _x.length, _x.width,) = _get_struct_iB2f().unpack(str[start:end])
        start = end
        end += 4
        (length,) = _struct_I.unpack(str[start:end])
        start = end
        end += length
        if python3:
          val1.to_string = str[start:end].decode('utf-8')
        else:
          val1.to_string = str[start:end]
        start = end
        end += 4
        (length,) = _struct_I.unpack(str[start:end])
        val1.bone_list = []
        for i in range(0, length):
          val2 = leap_motion.msg.Bone()
          _v33 = val2.header
          start = end
          end += 4
          (_v33.seq,) = _get_struct_I().unpack(str[start:end])
          _v34 = _v33.stamp
          _x = _v34
          start = end
          end += 8
          (_x.secs, _x.nsecs,) = _get_struct_2I().unpack(str[start:end])
          start = end
          end += 4
          (length,) = _struct_I.unpack(str[start:end])
          start = end
          end += length
          if python3:
            _v33.frame_id = str[start:end].decode('utf-8')
          else:
            _v33.frame_id = str[start:end]
          _x = val2
          start = end
          end += 9
          (_x.type, _x.length, _x.width,) = _get_struct_B2f().unpack(str[start:end])
          start = end
          end += 4
          (length,) = _struct_I.unpack(str[start:end])
          start = end
          end += length
          if python3:
            val2.to_string = str[start:end].decode('utf-8')
          else:
            val2.to_string = str[start:end]
          _v35 = val2.bone_start
          _v36 = _v35.position
          _x = _v36
          start = end
          end += 24
          (_x.x, _x.y, _x.z,) = _get_struct_3d().unpack(str[start:end])
          _v37 = _v35.orientation
          _x = _v37
          start = end
          end += 32
          (_x.x, _x.y, _x.z, _x.w,) = _get_struct_4d().unpack(str[start:end])
          _v38 = val2.bone_end
          _v39 = _v38.position
          _x = _v39
          start = end
          end += 24
          (_x.x, _x.y, _x.z,) = _get_struct_3d().unpack(str[start:end])
          _v40 = _v38.orientation
          _x = _v40
          start = end
          end += 32
          (_x.x, _x.y, _x.z, _x.w,) = _get_struct_4d().unpack(str[start:end])
          start = end
          end += 4
          (length,) = _struct_I.unpack(str[start:end])
          pattern = '<%sf'%length
          start = end
          end += struct.calcsize(pattern)
          val2.center = struct.unpack(pattern, str[start:end])
          val1.bone_list.append(val2)
        self.left_hand.finger_list.append(val1)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.left_hand.gesture_list = []
      for i in range(0, length):
        val1 = leap_motion.msg.Gesture()
        _x = val1
        start = end
        end += 25
        (_x.lmc_gesture_id, _x.is_valid, _x.duration_us, _x.duration_s, _x.gesture_state, _x.gesture_type,) = _get_struct_iBqf2i().unpack(str[start:end])
        val1.is_valid = bool(val1.is_valid)
        start = end
        end += 4
        (length,) = _struct_I.unpack(str[start:end])
        start = end
        end += length
        if python3:
          val1.to_string = str[start:end].decode('utf-8')
        else:
          val1.to_string = str[start:end]
        start = end
        end += 4
        (length,) = _struct_I.unpack(str[start:end])
        pattern = '<%si'%length
        start = end
        end += struct.calcsize(pattern)
        val1.pointable_ids = struct.unpack(pattern, str[start:end])
        self.left_hand.gesture_list.append(val1)
      _x = self
      start = end
      end += 12
      (_x.left_hand.arm.header.seq, _x.left_hand.arm.header.stamp.secs, _x.left_hand.arm.header.stamp.nsecs,) = _get_struct_3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.left_hand.arm.header.frame_id = str[start:end].decode('utf-8')
      else:
        self.left_hand.arm.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 112
      (_x.left_hand.arm.elbow.position.x, _x.left_hand.arm.elbow.position.y, _x.left_hand.arm.elbow.position.z, _x.left_hand.arm.elbow.orientation.x, _x.left_hand.arm.elbow.orientation.y, _x.left_hand.arm.elbow.orientation.z, _x.left_hand.arm.elbow.orientation.w, _x.left_hand.arm.wrist.position.x, _x.left_hand.arm.wrist.position.y, _x.left_hand.arm.wrist.position.z, _x.left_hand.arm.wrist.orientation.x, _x.left_hand.arm.wrist.orientation.y, _x.left_hand.arm.wrist.orientation.z, _x.left_hand.arm.wrist.orientation.w,) = _get_struct_14d().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%sf'%length
      start = end
      end += struct.calcsize(pattern)
      self.left_hand.arm.center = struct.unpack(pattern, str[start:end])
      _x = self
      start = end
      end += 24
      (_x.left_hand.arm.direction.x, _x.left_hand.arm.direction.y, _x.left_hand.arm.direction.z,) = _get_struct_3d().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_3I().pack(_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs))
      _x = self.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.pack('<I%ss'%length, length, _x))
      _x = self
      buff.write(_get_struct_4if().pack(_x.lmc_frame_id, _x.nr_of_hands, _x.nr_of_fingers, _x.nr_of_gestures, _x.current_frames_per_second))
      _x = self.to_string
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.pack('<I%ss'%length, length, _x))
      _x = self
      buff.write(_get_struct_3I().pack(_x.right_hand.header.seq, _x.right_hand.header.stamp.secs, _x.right_hand.header.stamp.nsecs))
      _x = self.right_hand.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.pack('<I%ss'%length, length, _x))
      _x = self
      buff.write(_get_struct_i2B5f6d2f().pack(_x.right_hand.lmc_hand_id, _x.right_hand.is_present, _x.right_hand.valid_gestures, _x.right_hand.time_visible, _x.right_hand.confidence, _x.right_hand.roll, _x.right_hand.pitch, _x.right_hand.yaw, _x.right_hand.direction.x, _x.right_hand.direction.y, _x.right_hand.direction.z, _x.right_hand.normal.x, _x.right_hand.normal.y, _x.right_hand.normal.z, _x.right_hand.grab_strength, _x.right_hand.pinch_strength))
      length = len(self.right_hand.palm_velocity)
      buff.write(_struct_I.pack(length))
      pattern = '<%sf'%length
      buff.write(self.right_hand.palm_velocity.tostring())
      _x = self
      buff.write(_get_struct_3d2f().pack(_x.right_hand.palm_center.x, _x.right_hand.palm_center.y, _x.right_hand.palm_center.z, _x.right_hand.palm_width, _x.right_hand.sphere_radius))
      length = len(self.right_hand.sphere_center)
      buff.write(_struct_I.pack(length))
      pattern = '<%sf'%length
      buff.write(self.right_hand.sphere_center.tostring())
      _x = self.right_hand.to_string
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.pack('<I%ss'%length, length, _x))
      length = len(self.right_hand.finger_list)
      buff.write(_struct_I.pack(length))
      for val1 in self.right_hand.finger_list:
        _v41 = val1.header
        buff.write(_get_struct_I().pack(_v41.seq))
        _v42 = _v41.stamp
        _x = _v42
        buff.write(_get_struct_2I().pack(_x.secs, _x.nsecs))
        _x = _v41.frame_id
        length = len(_x)
        if python3 or type(_x) == unicode:
          _x = _x.encode('utf-8')
          length = len(_x)
        buff.write(struct.pack('<I%ss'%length, length, _x))
        _x = val1
        buff.write(_get_struct_iB2f().pack(_x.lmc_finger_id, _x.type, _x.length, _x.width))
        _x = val1.to_string
        length = len(_x)
        if python3 or type(_x) == unicode:
          _x = _x.encode('utf-8')
          length = len(_x)
        buff.write(struct.pack('<I%ss'%length, length, _x))
        length = len(val1.bone_list)
        buff.write(_struct_I.pack(length))
        for val2 in val1.bone_list:
          _v43 = val2.header
          buff.write(_get_struct_I().pack(_v43.seq))
          _v44 = _v43.stamp
          _x = _v44
          buff.write(_get_struct_2I().pack(_x.secs, _x.nsecs))
          _x = _v43.frame_id
          length = len(_x)
          if python3 or type(_x) == unicode:
            _x = _x.encode('utf-8')
            length = len(_x)
          buff.write(struct.pack('<I%ss'%length, length, _x))
          _x = val2
          buff.write(_get_struct_B2f().pack(_x.type, _x.length, _x.width))
          _x = val2.to_string
          length = len(_x)
          if python3 or type(_x) == unicode:
            _x = _x.encode('utf-8')
            length = len(_x)
          buff.write(struct.pack('<I%ss'%length, length, _x))
          _v45 = val2.bone_start
          _v46 = _v45.position
          _x = _v46
          buff.write(_get_struct_3d().pack(_x.x, _x.y, _x.z))
          _v47 = _v45.orientation
          _x = _v47
          buff.write(_get_struct_4d().pack(_x.x, _x.y, _x.z, _x.w))
          _v48 = val2.bone_end
          _v49 = _v48.position
          _x = _v49
          buff.write(_get_struct_3d().pack(_x.x, _x.y, _x.z))
          _v50 = _v48.orientation
          _x = _v50
          buff.write(_get_struct_4d().pack(_x.x, _x.y, _x.z, _x.w))
          length = len(val2.center)
          buff.write(_struct_I.pack(length))
          pattern = '<%sf'%length
          buff.write(val2.center.tostring())
      length = len(self.right_hand.gesture_list)
      buff.write(_struct_I.pack(length))
      for val1 in self.right_hand.gesture_list:
        _x = val1
        buff.write(_get_struct_iBqf2i().pack(_x.lmc_gesture_id, _x.is_valid, _x.duration_us, _x.duration_s, _x.gesture_state, _x.gesture_type))
        _x = val1.to_string
        length = len(_x)
        if python3 or type(_x) == unicode:
          _x = _x.encode('utf-8')
          length = len(_x)
        buff.write(struct.pack('<I%ss'%length, length, _x))
        length = len(val1.pointable_ids)
        buff.write(_struct_I.pack(length))
        pattern = '<%si'%length
        buff.write(val1.pointable_ids.tostring())
      _x = self
      buff.write(_get_struct_3I().pack(_x.right_hand.arm.header.seq, _x.right_hand.arm.header.stamp.secs, _x.right_hand.arm.header.stamp.nsecs))
      _x = self.right_hand.arm.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.pack('<I%ss'%length, length, _x))
      _x = self
      buff.write(_get_struct_14d().pack(_x.right_hand.arm.elbow.position.x, _x.right_hand.arm.elbow.position.y, _x.right_hand.arm.elbow.position.z, _x.right_hand.arm.elbow.orientation.x, _x.right_hand.arm.elbow.orientation.y, _x.right_hand.arm.elbow.orientation.z, _x.right_hand.arm.elbow.orientation.w, _x.right_hand.arm.wrist.position.x, _x.right_hand.arm.wrist.position.y, _x.right_hand.arm.wrist.position.z, _x.right_hand.arm.wrist.orientation.x, _x.right_hand.arm.wrist.orientation.y, _x.right_hand.arm.wrist.orientation.z, _x.right_hand.arm.wrist.orientation.w))
      length = len(self.right_hand.arm.center)
      buff.write(_struct_I.pack(length))
      pattern = '<%sf'%length
      buff.write(self.right_hand.arm.center.tostring())
      _x = self
      buff.write(_get_struct_3d3I().pack(_x.right_hand.arm.direction.x, _x.right_hand.arm.direction.y, _x.right_hand.arm.direction.z, _x.left_hand.header.seq, _x.left_hand.header.stamp.secs, _x.left_hand.header.stamp.nsecs))
      _x = self.left_hand.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.pack('<I%ss'%length, length, _x))
      _x = self
      buff.write(_get_struct_i2B5f6d2f().pack(_x.left_hand.lmc_hand_id, _x.left_hand.is_present, _x.left_hand.valid_gestures, _x.left_hand.time_visible, _x.left_hand.confidence, _x.left_hand.roll, _x.left_hand.pitch, _x.left_hand.yaw, _x.left_hand.direction.x, _x.left_hand.direction.y, _x.left_hand.direction.z, _x.left_hand.normal.x, _x.left_hand.normal.y, _x.left_hand.normal.z, _x.left_hand.grab_strength, _x.left_hand.pinch_strength))
      length = len(self.left_hand.palm_velocity)
      buff.write(_struct_I.pack(length))
      pattern = '<%sf'%length
      buff.write(self.left_hand.palm_velocity.tostring())
      _x = self
      buff.write(_get_struct_3d2f().pack(_x.left_hand.palm_center.x, _x.left_hand.palm_center.y, _x.left_hand.palm_center.z, _x.left_hand.palm_width, _x.left_hand.sphere_radius))
      length = len(self.left_hand.sphere_center)
      buff.write(_struct_I.pack(length))
      pattern = '<%sf'%length
      buff.write(self.left_hand.sphere_center.tostring())
      _x = self.left_hand.to_string
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.pack('<I%ss'%length, length, _x))
      length = len(self.left_hand.finger_list)
      buff.write(_struct_I.pack(length))
      for val1 in self.left_hand.finger_list:
        _v51 = val1.header
        buff.write(_get_struct_I().pack(_v51.seq))
        _v52 = _v51.stamp
        _x = _v52
        buff.write(_get_struct_2I().pack(_x.secs, _x.nsecs))
        _x = _v51.frame_id
        length = len(_x)
        if python3 or type(_x) == unicode:
          _x = _x.encode('utf-8')
          length = len(_x)
        buff.write(struct.pack('<I%ss'%length, length, _x))
        _x = val1
        buff.write(_get_struct_iB2f().pack(_x.lmc_finger_id, _x.type, _x.length, _x.width))
        _x = val1.to_string
        length = len(_x)
        if python3 or type(_x) == unicode:
          _x = _x.encode('utf-8')
          length = len(_x)
        buff.write(struct.pack('<I%ss'%length, length, _x))
        length = len(val1.bone_list)
        buff.write(_struct_I.pack(length))
        for val2 in val1.bone_list:
          _v53 = val2.header
          buff.write(_get_struct_I().pack(_v53.seq))
          _v54 = _v53.stamp
          _x = _v54
          buff.write(_get_struct_2I().pack(_x.secs, _x.nsecs))
          _x = _v53.frame_id
          length = len(_x)
          if python3 or type(_x) == unicode:
            _x = _x.encode('utf-8')
            length = len(_x)
          buff.write(struct.pack('<I%ss'%length, length, _x))
          _x = val2
          buff.write(_get_struct_B2f().pack(_x.type, _x.length, _x.width))
          _x = val2.to_string
          length = len(_x)
          if python3 or type(_x) == unicode:
            _x = _x.encode('utf-8')
            length = len(_x)
          buff.write(struct.pack('<I%ss'%length, length, _x))
          _v55 = val2.bone_start
          _v56 = _v55.position
          _x = _v56
          buff.write(_get_struct_3d().pack(_x.x, _x.y, _x.z))
          _v57 = _v55.orientation
          _x = _v57
          buff.write(_get_struct_4d().pack(_x.x, _x.y, _x.z, _x.w))
          _v58 = val2.bone_end
          _v59 = _v58.position
          _x = _v59
          buff.write(_get_struct_3d().pack(_x.x, _x.y, _x.z))
          _v60 = _v58.orientation
          _x = _v60
          buff.write(_get_struct_4d().pack(_x.x, _x.y, _x.z, _x.w))
          length = len(val2.center)
          buff.write(_struct_I.pack(length))
          pattern = '<%sf'%length
          buff.write(val2.center.tostring())
      length = len(self.left_hand.gesture_list)
      buff.write(_struct_I.pack(length))
      for val1 in self.left_hand.gesture_list:
        _x = val1
        buff.write(_get_struct_iBqf2i().pack(_x.lmc_gesture_id, _x.is_valid, _x.duration_us, _x.duration_s, _x.gesture_state, _x.gesture_type))
        _x = val1.to_string
        length = len(_x)
        if python3 or type(_x) == unicode:
          _x = _x.encode('utf-8')
          length = len(_x)
        buff.write(struct.pack('<I%ss'%length, length, _x))
        length = len(val1.pointable_ids)
        buff.write(_struct_I.pack(length))
        pattern = '<%si'%length
        buff.write(val1.pointable_ids.tostring())
      _x = self
      buff.write(_get_struct_3I().pack(_x.left_hand.arm.header.seq, _x.left_hand.arm.header.stamp.secs, _x.left_hand.arm.header.stamp.nsecs))
      _x = self.left_hand.arm.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.pack('<I%ss'%length, length, _x))
      _x = self
      buff.write(_get_struct_14d().pack(_x.left_hand.arm.elbow.position.x, _x.left_hand.arm.elbow.position.y, _x.left_hand.arm.elbow.position.z, _x.left_hand.arm.elbow.orientation.x, _x.left_hand.arm.elbow.orientation.y, _x.left_hand.arm.elbow.orientation.z, _x.left_hand.arm.elbow.orientation.w, _x.left_hand.arm.wrist.position.x, _x.left_hand.arm.wrist.position.y, _x.left_hand.arm.wrist.position.z, _x.left_hand.arm.wrist.orientation.x, _x.left_hand.arm.wrist.orientation.y, _x.left_hand.arm.wrist.orientation.z, _x.left_hand.arm.wrist.orientation.w))
      length = len(self.left_hand.arm.center)
      buff.write(_struct_I.pack(length))
      pattern = '<%sf'%length
      buff.write(self.left_hand.arm.center.tostring())
      _x = self
      buff.write(_get_struct_3d().pack(_x.left_hand.arm.direction.x, _x.left_hand.arm.direction.y, _x.left_hand.arm.direction.z))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      if self.header is None:
        self.header = std_msgs.msg.Header()
      if self.right_hand is None:
        self.right_hand = leap_motion.msg.Hand()
      if self.left_hand is None:
        self.left_hand = leap_motion.msg.Hand()
      end = 0
      _x = self
      start = end
      end += 12
      (_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs,) = _get_struct_3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.header.frame_id = str[start:end].decode('utf-8')
      else:
        self.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 20
      (_x.lmc_frame_id, _x.nr_of_hands, _x.nr_of_fingers, _x.nr_of_gestures, _x.current_frames_per_second,) = _get_struct_4if().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.to_string = str[start:end].decode('utf-8')
      else:
        self.to_string = str[start:end]
      _x = self
      start = end
      end += 12
      (_x.right_hand.header.seq, _x.right_hand.header.stamp.secs, _x.right_hand.header.stamp.nsecs,) = _get_struct_3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.right_hand.header.frame_id = str[start:end].decode('utf-8')
      else:
        self.right_hand.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 82
      (_x.right_hand.lmc_hand_id, _x.right_hand.is_present, _x.right_hand.valid_gestures, _x.right_hand.time_visible, _x.right_hand.confidence, _x.right_hand.roll, _x.right_hand.pitch, _x.right_hand.yaw, _x.right_hand.direction.x, _x.right_hand.direction.y, _x.right_hand.direction.z, _x.right_hand.normal.x, _x.right_hand.normal.y, _x.right_hand.normal.z, _x.right_hand.grab_strength, _x.right_hand.pinch_strength,) = _get_struct_i2B5f6d2f().unpack(str[start:end])
      self.right_hand.is_present = bool(self.right_hand.is_present)
      self.right_hand.valid_gestures = bool(self.right_hand.valid_gestures)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%sf'%length
      start = end
      end += struct.calcsize(pattern)
      self.right_hand.palm_velocity = numpy.frombuffer(str[start:end], dtype=numpy.float32, count=length)
      _x = self
      start = end
      end += 32
      (_x.right_hand.palm_center.x, _x.right_hand.palm_center.y, _x.right_hand.palm_center.z, _x.right_hand.palm_width, _x.right_hand.sphere_radius,) = _get_struct_3d2f().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%sf'%length
      start = end
      end += struct.calcsize(pattern)
      self.right_hand.sphere_center = numpy.frombuffer(str[start:end], dtype=numpy.float32, count=length)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.right_hand.to_string = str[start:end].decode('utf-8')
      else:
        self.right_hand.to_string = str[start:end]
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.right_hand.finger_list = []
      for i in range(0, length):
        val1 = leap_motion.msg.Finger()
        _v61 = val1.header
        start = end
        end += 4
        (_v61.seq,) = _get_struct_I().unpack(str[start:end])
        _v62 = _v61.stamp
        _x = _v62
        start = end
        end += 8
        (_x.secs, _x.nsecs,) = _get_struct_2I().unpack(str[start:end])
        start = end
        end += 4
        (length,) = _struct_I.unpack(str[start:end])
        start = end
        end += length
        if python3:
          _v61.frame_id = str[start:end].decode('utf-8')
        else:
          _v61.frame_id = str[start:end]
        _x = val1
        start = end
        end += 13
        (_x.lmc_finger_id, _x.type, _x.length, _x.width,) = _get_struct_iB2f().unpack(str[start:end])
        start = end
        end += 4
        (length,) = _struct_I.unpack(str[start:end])
        start = end
        end += length
        if python3:
          val1.to_string = str[start:end].decode('utf-8')
        else:
          val1.to_string = str[start:end]
        start = end
        end += 4
        (length,) = _struct_I.unpack(str[start:end])
        val1.bone_list = []
        for i in range(0, length):
          val2 = leap_motion.msg.Bone()
          _v63 = val2.header
          start = end
          end += 4
          (_v63.seq,) = _get_struct_I().unpack(str[start:end])
          _v64 = _v63.stamp
          _x = _v64
          start = end
          end += 8
          (_x.secs, _x.nsecs,) = _get_struct_2I().unpack(str[start:end])
          start = end
          end += 4
          (length,) = _struct_I.unpack(str[start:end])
          start = end
          end += length
          if python3:
            _v63.frame_id = str[start:end].decode('utf-8')
          else:
            _v63.frame_id = str[start:end]
          _x = val2
          start = end
          end += 9
          (_x.type, _x.length, _x.width,) = _get_struct_B2f().unpack(str[start:end])
          start = end
          end += 4
          (length,) = _struct_I.unpack(str[start:end])
          start = end
          end += length
          if python3:
            val2.to_string = str[start:end].decode('utf-8')
          else:
            val2.to_string = str[start:end]
          _v65 = val2.bone_start
          _v66 = _v65.position
          _x = _v66
          start = end
          end += 24
          (_x.x, _x.y, _x.z,) = _get_struct_3d().unpack(str[start:end])
          _v67 = _v65.orientation
          _x = _v67
          start = end
          end += 32
          (_x.x, _x.y, _x.z, _x.w,) = _get_struct_4d().unpack(str[start:end])
          _v68 = val2.bone_end
          _v69 = _v68.position
          _x = _v69
          start = end
          end += 24
          (_x.x, _x.y, _x.z,) = _get_struct_3d().unpack(str[start:end])
          _v70 = _v68.orientation
          _x = _v70
          start = end
          end += 32
          (_x.x, _x.y, _x.z, _x.w,) = _get_struct_4d().unpack(str[start:end])
          start = end
          end += 4
          (length,) = _struct_I.unpack(str[start:end])
          pattern = '<%sf'%length
          start = end
          end += struct.calcsize(pattern)
          val2.center = numpy.frombuffer(str[start:end], dtype=numpy.float32, count=length)
          val1.bone_list.append(val2)
        self.right_hand.finger_list.append(val1)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.right_hand.gesture_list = []
      for i in range(0, length):
        val1 = leap_motion.msg.Gesture()
        _x = val1
        start = end
        end += 25
        (_x.lmc_gesture_id, _x.is_valid, _x.duration_us, _x.duration_s, _x.gesture_state, _x.gesture_type,) = _get_struct_iBqf2i().unpack(str[start:end])
        val1.is_valid = bool(val1.is_valid)
        start = end
        end += 4
        (length,) = _struct_I.unpack(str[start:end])
        start = end
        end += length
        if python3:
          val1.to_string = str[start:end].decode('utf-8')
        else:
          val1.to_string = str[start:end]
        start = end
        end += 4
        (length,) = _struct_I.unpack(str[start:end])
        pattern = '<%si'%length
        start = end
        end += struct.calcsize(pattern)
        val1.pointable_ids = numpy.frombuffer(str[start:end], dtype=numpy.int32, count=length)
        self.right_hand.gesture_list.append(val1)
      _x = self
      start = end
      end += 12
      (_x.right_hand.arm.header.seq, _x.right_hand.arm.header.stamp.secs, _x.right_hand.arm.header.stamp.nsecs,) = _get_struct_3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.right_hand.arm.header.frame_id = str[start:end].decode('utf-8')
      else:
        self.right_hand.arm.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 112
      (_x.right_hand.arm.elbow.position.x, _x.right_hand.arm.elbow.position.y, _x.right_hand.arm.elbow.position.z, _x.right_hand.arm.elbow.orientation.x, _x.right_hand.arm.elbow.orientation.y, _x.right_hand.arm.elbow.orientation.z, _x.right_hand.arm.elbow.orientation.w, _x.right_hand.arm.wrist.position.x, _x.right_hand.arm.wrist.position.y, _x.right_hand.arm.wrist.position.z, _x.right_hand.arm.wrist.orientation.x, _x.right_hand.arm.wrist.orientation.y, _x.right_hand.arm.wrist.orientation.z, _x.right_hand.arm.wrist.orientation.w,) = _get_struct_14d().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%sf'%length
      start = end
      end += struct.calcsize(pattern)
      self.right_hand.arm.center = numpy.frombuffer(str[start:end], dtype=numpy.float32, count=length)
      _x = self
      start = end
      end += 36
      (_x.right_hand.arm.direction.x, _x.right_hand.arm.direction.y, _x.right_hand.arm.direction.z, _x.left_hand.header.seq, _x.left_hand.header.stamp.secs, _x.left_hand.header.stamp.nsecs,) = _get_struct_3d3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.left_hand.header.frame_id = str[start:end].decode('utf-8')
      else:
        self.left_hand.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 82
      (_x.left_hand.lmc_hand_id, _x.left_hand.is_present, _x.left_hand.valid_gestures, _x.left_hand.time_visible, _x.left_hand.confidence, _x.left_hand.roll, _x.left_hand.pitch, _x.left_hand.yaw, _x.left_hand.direction.x, _x.left_hand.direction.y, _x.left_hand.direction.z, _x.left_hand.normal.x, _x.left_hand.normal.y, _x.left_hand.normal.z, _x.left_hand.grab_strength, _x.left_hand.pinch_strength,) = _get_struct_i2B5f6d2f().unpack(str[start:end])
      self.left_hand.is_present = bool(self.left_hand.is_present)
      self.left_hand.valid_gestures = bool(self.left_hand.valid_gestures)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%sf'%length
      start = end
      end += struct.calcsize(pattern)
      self.left_hand.palm_velocity = numpy.frombuffer(str[start:end], dtype=numpy.float32, count=length)
      _x = self
      start = end
      end += 32
      (_x.left_hand.palm_center.x, _x.left_hand.palm_center.y, _x.left_hand.palm_center.z, _x.left_hand.palm_width, _x.left_hand.sphere_radius,) = _get_struct_3d2f().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%sf'%length
      start = end
      end += struct.calcsize(pattern)
      self.left_hand.sphere_center = numpy.frombuffer(str[start:end], dtype=numpy.float32, count=length)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.left_hand.to_string = str[start:end].decode('utf-8')
      else:
        self.left_hand.to_string = str[start:end]
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.left_hand.finger_list = []
      for i in range(0, length):
        val1 = leap_motion.msg.Finger()
        _v71 = val1.header
        start = end
        end += 4
        (_v71.seq,) = _get_struct_I().unpack(str[start:end])
        _v72 = _v71.stamp
        _x = _v72
        start = end
        end += 8
        (_x.secs, _x.nsecs,) = _get_struct_2I().unpack(str[start:end])
        start = end
        end += 4
        (length,) = _struct_I.unpack(str[start:end])
        start = end
        end += length
        if python3:
          _v71.frame_id = str[start:end].decode('utf-8')
        else:
          _v71.frame_id = str[start:end]
        _x = val1
        start = end
        end += 13
        (_x.lmc_finger_id, _x.type, _x.length, _x.width,) = _get_struct_iB2f().unpack(str[start:end])
        start = end
        end += 4
        (length,) = _struct_I.unpack(str[start:end])
        start = end
        end += length
        if python3:
          val1.to_string = str[start:end].decode('utf-8')
        else:
          val1.to_string = str[start:end]
        start = end
        end += 4
        (length,) = _struct_I.unpack(str[start:end])
        val1.bone_list = []
        for i in range(0, length):
          val2 = leap_motion.msg.Bone()
          _v73 = val2.header
          start = end
          end += 4
          (_v73.seq,) = _get_struct_I().unpack(str[start:end])
          _v74 = _v73.stamp
          _x = _v74
          start = end
          end += 8
          (_x.secs, _x.nsecs,) = _get_struct_2I().unpack(str[start:end])
          start = end
          end += 4
          (length,) = _struct_I.unpack(str[start:end])
          start = end
          end += length
          if python3:
            _v73.frame_id = str[start:end].decode('utf-8')
          else:
            _v73.frame_id = str[start:end]
          _x = val2
          start = end
          end += 9
          (_x.type, _x.length, _x.width,) = _get_struct_B2f().unpack(str[start:end])
          start = end
          end += 4
          (length,) = _struct_I.unpack(str[start:end])
          start = end
          end += length
          if python3:
            val2.to_string = str[start:end].decode('utf-8')
          else:
            val2.to_string = str[start:end]
          _v75 = val2.bone_start
          _v76 = _v75.position
          _x = _v76
          start = end
          end += 24
          (_x.x, _x.y, _x.z,) = _get_struct_3d().unpack(str[start:end])
          _v77 = _v75.orientation
          _x = _v77
          start = end
          end += 32
          (_x.x, _x.y, _x.z, _x.w,) = _get_struct_4d().unpack(str[start:end])
          _v78 = val2.bone_end
          _v79 = _v78.position
          _x = _v79
          start = end
          end += 24
          (_x.x, _x.y, _x.z,) = _get_struct_3d().unpack(str[start:end])
          _v80 = _v78.orientation
          _x = _v80
          start = end
          end += 32
          (_x.x, _x.y, _x.z, _x.w,) = _get_struct_4d().unpack(str[start:end])
          start = end
          end += 4
          (length,) = _struct_I.unpack(str[start:end])
          pattern = '<%sf'%length
          start = end
          end += struct.calcsize(pattern)
          val2.center = numpy.frombuffer(str[start:end], dtype=numpy.float32, count=length)
          val1.bone_list.append(val2)
        self.left_hand.finger_list.append(val1)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.left_hand.gesture_list = []
      for i in range(0, length):
        val1 = leap_motion.msg.Gesture()
        _x = val1
        start = end
        end += 25
        (_x.lmc_gesture_id, _x.is_valid, _x.duration_us, _x.duration_s, _x.gesture_state, _x.gesture_type,) = _get_struct_iBqf2i().unpack(str[start:end])
        val1.is_valid = bool(val1.is_valid)
        start = end
        end += 4
        (length,) = _struct_I.unpack(str[start:end])
        start = end
        end += length
        if python3:
          val1.to_string = str[start:end].decode('utf-8')
        else:
          val1.to_string = str[start:end]
        start = end
        end += 4
        (length,) = _struct_I.unpack(str[start:end])
        pattern = '<%si'%length
        start = end
        end += struct.calcsize(pattern)
        val1.pointable_ids = numpy.frombuffer(str[start:end], dtype=numpy.int32, count=length)
        self.left_hand.gesture_list.append(val1)
      _x = self
      start = end
      end += 12
      (_x.left_hand.arm.header.seq, _x.left_hand.arm.header.stamp.secs, _x.left_hand.arm.header.stamp.nsecs,) = _get_struct_3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.left_hand.arm.header.frame_id = str[start:end].decode('utf-8')
      else:
        self.left_hand.arm.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 112
      (_x.left_hand.arm.elbow.position.x, _x.left_hand.arm.elbow.position.y, _x.left_hand.arm.elbow.position.z, _x.left_hand.arm.elbow.orientation.x, _x.left_hand.arm.elbow.orientation.y, _x.left_hand.arm.elbow.orientation.z, _x.left_hand.arm.elbow.orientation.w, _x.left_hand.arm.wrist.position.x, _x.left_hand.arm.wrist.position.y, _x.left_hand.arm.wrist.position.z, _x.left_hand.arm.wrist.orientation.x, _x.left_hand.arm.wrist.orientation.y, _x.left_hand.arm.wrist.orientation.z, _x.left_hand.arm.wrist.orientation.w,) = _get_struct_14d().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%sf'%length
      start = end
      end += struct.calcsize(pattern)
      self.left_hand.arm.center = numpy.frombuffer(str[start:end], dtype=numpy.float32, count=length)
      _x = self
      start = end
      end += 24
      (_x.left_hand.arm.direction.x, _x.left_hand.arm.direction.y, _x.left_hand.arm.direction.z,) = _get_struct_3d().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_3d3I = None
def _get_struct_3d3I():
    global _struct_3d3I
    if _struct_3d3I is None:
        _struct_3d3I = struct.Struct("<3d3I")
    return _struct_3d3I
_struct_iBqf2i = None
def _get_struct_iBqf2i():
    global _struct_iBqf2i
    if _struct_iBqf2i is None:
        _struct_iBqf2i = struct.Struct("<iBqf2i")
    return _struct_iBqf2i
_struct_iB2f = None
def _get_struct_iB2f():
    global _struct_iB2f
    if _struct_iB2f is None:
        _struct_iB2f = struct.Struct("<iB2f")
    return _struct_iB2f
_struct_3d2f = None
def _get_struct_3d2f():
    global _struct_3d2f
    if _struct_3d2f is None:
        _struct_3d2f = struct.Struct("<3d2f")
    return _struct_3d2f
_struct_14d = None
def _get_struct_14d():
    global _struct_14d
    if _struct_14d is None:
        _struct_14d = struct.Struct("<14d")
    return _struct_14d
_struct_4d = None
def _get_struct_4d():
    global _struct_4d
    if _struct_4d is None:
        _struct_4d = struct.Struct("<4d")
    return _struct_4d
_struct_3I = None
def _get_struct_3I():
    global _struct_3I
    if _struct_3I is None:
        _struct_3I = struct.Struct("<3I")
    return _struct_3I
_struct_i2B5f6d2f = None
def _get_struct_i2B5f6d2f():
    global _struct_i2B5f6d2f
    if _struct_i2B5f6d2f is None:
        _struct_i2B5f6d2f = struct.Struct("<i2B5f6d2f")
    return _struct_i2B5f6d2f
_struct_B2f = None
def _get_struct_B2f():
    global _struct_B2f
    if _struct_B2f is None:
        _struct_B2f = struct.Struct("<B2f")
    return _struct_B2f
_struct_4if = None
def _get_struct_4if():
    global _struct_4if
    if _struct_4if is None:
        _struct_4if = struct.Struct("<4if")
    return _struct_4if
_struct_2I = None
def _get_struct_2I():
    global _struct_2I
    if _struct_2I is None:
        _struct_2I = struct.Struct("<2I")
    return _struct_2I
_struct_3d = None
def _get_struct_3d():
    global _struct_3d
    if _struct_3d is None:
        _struct_3d = struct.Struct("<3d")
    return _struct_3d
