(cl:in-package leap_motion-msg)
(cl:export '(HEADER-VAL
          HEADER
          LMC_HAND_ID-VAL
          LMC_HAND_ID
          IS_PRESENT-VAL
          IS_PRESENT
          VALID_GESTURES-VAL
          VALID_GESTURES
          TIME_VISIBLE-VAL
          TIME_VISIBLE
          CONFIDENCE-VAL
          CONFIDENCE
          ROLL-VAL
          ROLL
          PITCH-VAL
          PITCH
          YAW-VAL
          YAW
          DIRECTION-VAL
          DIRECTION
          NORMAL-VAL
          NORMAL
          GRAB_STRENGTH-VAL
          GRAB_STRENGTH
          PINCH_STRENGTH-VAL
          PINCH_STRENGTH
          PALM_VELOCITY-VAL
          PALM_VELOCITY
          PALM_CENTER-VAL
          PALM_CENTER
          PALM_WIDTH-VAL
          PALM_WIDTH
          SPHERE_RADIUS-VAL
          SPHERE_RADIUS
          SPHERE_CENTER-VAL
          SPHERE_CENTER
          TO_STRING-VAL
          TO_STRING
          FINGER_LIST-VAL
          FINGER_LIST
          GESTURE_LIST-VAL
          GESTURE_LIST
          ARM-VAL
          ARM
))