# joint_limits.yaml allows the dynamics properties specified in the URDF to be overwritten or augmented as needed
# Specific joint properties can be changed with the keys [max_position, min_position, max_velocity, max_acceleration]
# Joint limits can be turned off with [has_velocity_limits, has_acceleration_limits]
joint_limits:
  leftelbow_joint:
    has_velocity_limits: true
    max_velocity: 2.25
    has_acceleration_limits: false
    max_acceleration: 2
  leftshoulder_lift_joint:
    has_velocity_limits: true
    max_velocity: 2.26
    has_acceleration_limits: false
    max_acceleration: 2
  leftshoulder_pan_joint:
    has_velocity_limits: true
    max_velocity: 2.26
    has_acceleration_limits: false
    max_acceleration: 2
  leftwrist_1_joint:
    has_velocity_limits: true
    max_velocity: 2.1
    has_acceleration_limits: false
    max_acceleration: 2
  leftwrist_2_joint:
    has_velocity_limits: true
    max_velocity: 2.1
    has_acceleration_limits: false
    max_acceleration: 2
  leftwrist_3_joint:
    has_velocity_limits: true
    max_velocity: 2.1
    has_acceleration_limits: false
    max_acceleration: 2
  rightelbow_joint:
    has_velocity_limits: true
    max_velocity: 2.25
    has_acceleration_limits: false
    max_acceleration: 2
  rightshoulder_lift_joint:
    has_velocity_limits: true
    max_velocity: 2.26
    has_acceleration_limits: false
    max_acceleration: 2
  rightshoulder_pan_joint:
    has_velocity_limits: true
    max_velocity: 2.26
    has_acceleration_limits: false
    max_acceleration: 2
  rightwrist_1_joint:
    has_velocity_limits: true
    max_velocity: 2.1
    has_acceleration_limits: false
    max_acceleration: 2
  rightwrist_2_joint:
    has_velocity_limits: true
    max_velocity: 2.1
    has_acceleration_limits: false
    max_acceleration: 2
  rightwrist_3_joint:
    has_velocity_limits: true
    max_velocity: 2.1
    has_acceleration_limits: false
    max_acceleration: 2