# joint_limits.yaml allows the dynamics properties specified in the URDF to be overwritten or augmented as needed
# Specific joint properties can be changed with the keys [max_position, min_position, max_velocity, max_acceleration]
# Joint limits can be turned off with [has_velocity_limits, has_acceleration_limits]
joint_limits:
  leftelbow_joint:
    has_velocity_limits: true
    max_velocity: 0.15
    has_acceleration_limits: false
    max_acceleration: 0
  leftshoulder_lift_joint:
    has_velocity_limits: true
    max_velocity: 0.16
    has_acceleration_limits: false
    max_acceleration: 0
  leftshoulder_pan_joint:
    has_velocity_limits: true
    max_velocity: 0.16
    has_acceleration_limits: false
    max_acceleration: 0
  leftwrist_1_joint:
    has_velocity_limits: true
    max_velocity: 0.2
    has_acceleration_limits: false
    max_acceleration: 0
  leftwrist_2_joint:
    has_velocity_limits: true
    max_velocity: 0.2
    has_acceleration_limits: false
    max_acceleration: 0
  leftwrist_3_joint:
    has_velocity_limits: true
    max_velocity: 0.2
    has_acceleration_limits: false
    max_acceleration: 0
  rightelbow_joint:
    has_velocity_limits: true
    max_velocity: 0.15
    has_acceleration_limits: false
    max_acceleration: 0
  rightshoulder_lift_joint:
    has_velocity_limits: true
    max_velocity: 0.16
    has_acceleration_limits: false
    max_acceleration: 0
  rightshoulder_pan_joint:
    has_velocity_limits: true
    max_velocity: 0.16
    has_acceleration_limits: false
    max_acceleration: 0
  rightwrist_1_joint:
    has_velocity_limits: true
    max_velocity: 0.2
    has_acceleration_limits: false
    max_acceleration: 0
  rightwrist_2_joint:
    has_velocity_limits: true
    max_velocity: 0.2
    has_acceleration_limits: false
    max_acceleration: 0
  rightwrist_3_joint:
    has_velocity_limits: true
    max_velocity: 0.2
    has_acceleration_limits: false
    max_acceleration: 0